USE sql_proyect;

-- Nota media que otorga cada profe
SELECT AVG(NOTA), PRO.NOMBRE FROM CALIFICACIONES CA 
JOIN PROFESORES PRO
ON CA.PROFESOR_DNI = PRO.DNI
WHERE PROFESOR_DNI IN (
	SELECT DNI FROM PROFESORES
) GROUP BY PROFESOR_DNI;

-- Mejores calificaciones
SELECT MAX(NOTA) 'NOTA MEDIA', ES.NOMBRE FROM CALIFICACIONES CA 
JOIN ESTUDIANTES ES
ON CA.ESTUDIANTE_DNI = ES.DNI
WHERE ESTUDIANTE_DNI IN (
	SELECT DNI FROM ESTUDIANTES
) GROUP BY ESTUDIANTE_DNI;

-- Ordenar estudiantes por cursos inscritos
SELECT ES.NOMBRE, COUNT(DISTINCT CA.CURSO_NOMBRE) AS 'Nº Cursos'
FROM ESTUDIANTES ES
JOIN CALIFICACIONES CA ON ES.DNI = CA.ESTUDIANTE_DNI
GROUP BY ES.DNI, ES.NOMBRE
ORDER BY 'Nº Cursos' ASC;

-- Informe resumido cursos y calificaciones promedio
SELECT CU.NOMBRE, AVG(CA.NOTA) FROM CALIFICACIONES CA
JOIN CURSOS CU
ON CU.NOMBRE = CA.CURSO_NOMBRE
GROUP BY CU.NOMBRE
ORDER BY AVG(CA.NOTA) ASC;

-- Estudiantes y profesor con cursos en comun
SELECT  ES.NOMBRE, PRO.NOMBRE FROM ESTUDIANTES ES
JOIN CALIFICACIONES CA
ON CA.ESTUDIANTE_DNI = ES.DNI
JOIN PROFESORES PRO
ON CA.PROFESOR_DNI = PRO.DNI
GROUP BY CA.PROFESOR_DNI, CA.ESTUDIANTE_DNI
ORDER BY MAX(CA.CURSO_NOMBRE) DESC;